version: '3.3'

services:
  bot:
    image: "selflove_bot"
    stop_signal: SIGINT
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    build:
      context: .
    command: "/usr/src/bot/docker-entrypoint.sh"
    restart: always
    env_file:
      - ".env"
