version: '3.3'

services:
  bot:
    image: "selflove_bot"
    stop_signal: SIGINT
    working_dir: "/usr/src/bot"
    volumes:
      - .:/usr/src/bot
    build:
      context: .
    command: "alembic upgrade head >&1 && python3 -m bot"
    restart: always
    env_file:
      - ".env"
