"""empty message

Revision ID: 0d08114bfb90
Revises: 5c9e3283ce3e
Create Date: 2024-02-05 10:00:50.556027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d08114bfb90'
down_revision: Union[str, None] = '5c9e3283ce3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_options', sa.Column('answer_index', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_options', 'answer_index')
    # ### end Alembic commands ###
