"""empty message

Revision ID: 119296cd3671
Revises: 7706e10b5daa
Create Date: 2024-01-14 23:09:17.434884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119296cd3671'
down_revision: Union[str, None] = '7706e10b5daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_options', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_options', 'weight')
    # ### end Alembic commands ###
