"""empty message

Revision ID: 306a4193c973
Revises: 97e735cb03f6
Create Date: 2024-02-28 23:52:04.522752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306a4193c973'
down_revision: Union[str, None] = '97e735cb03f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion_records', sa.Column('emotion', sa.String(length=16), nullable=False))
    op.drop_column('emotion_records', 'emoton')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion_records', sa.Column('emoton', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_column('emotion_records', 'emotion')
    # ### end Alembic commands ###
