"""empty message

Revision ID: 3e8cd7e8289d
Revises: 059337ea1476
Create Date: 2024-02-04 17:49:18.775558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8cd7e8289d'
down_revision: Union[str, None] = '059337ea1476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supported_languages', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supported_languages', 'is_default')
    # ### end Alembic commands ###
