"""empty message

Revision ID: 4248d44ccc08
Revises: 73123ea745f9
Create Date: 2024-03-06 15:06:14.630012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4248d44ccc08'
down_revision: Union[str, None] = '73123ea745f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('poll_results_user_id_fkey', 'poll_results', type_='foreignkey')
    op.create_foreign_key(None, 'poll_results', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('sent_polls_user_id_fkey', 'sent_polls', type_='foreignkey')
    op.create_foreign_key(None, 'sent_polls', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sent_polls', type_='foreignkey')
    op.create_foreign_key('sent_polls_user_id_fkey', 'sent_polls', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'poll_results', type_='foreignkey')
    op.create_foreign_key('poll_results_user_id_fkey', 'poll_results', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
