"""empty message

Revision ID: 5400d88d7eb7
Revises: d7935c5d8888
Create Date: 2024-02-11 18:25:19.814613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5400d88d7eb7'
down_revision: Union[str, None] = 'd7935c5d8888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_results', sa.Column('severity_status', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_results', 'severity_status')
    # ### end Alembic commands ###
