"""empty message

Revision ID: 57c8d9fa3631
Revises: 0c9b0ae3dc0b
Create Date: 2024-02-05 09:54:09.877018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c8d9fa3631'
down_revision: Union[str, None] = '0c9b0ae3dc0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
