"""empty message

Revision ID: 5c9e3283ce3e
Revises: 4c5ef5b0859e
Create Date: 2024-02-05 09:57:50.599743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9e3283ce3e'
down_revision: Union[str, None] = '4c5ef5b0859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
