"""empty message

Revision ID: 5d6d82476c55
Revises: 69bef444c1a2
Create Date: 2024-01-30 11:24:17.484345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6d82476c55'
down_revision: Union[str, None] = '69bef444c1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communication_history', 'text',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communication_history', 'text',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
