"""empty message

Revision ID: 68f5dd99428b
Revises: d4d9015eadc3
Create Date: 2024-02-05 11:21:53.176022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f5dd99428b'
down_revision: Union[str, None] = 'd4d9015eadc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_polls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_polls',
    sa.Column('poll_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['communication_history.message_id'], name='sent_polls_message_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name='sent_polls_question_id_fkey'),
    sa.PrimaryKeyConstraint('poll_id', 'question_id', name='sent_polls_pkey')
    )
    # ### end Alembic commands ###
