"""empty message

Revision ID: 69bef444c1a2
Revises: e9e52fbe8017
Create Date: 2024-01-23 10:57:10.592688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bef444c1a2'
down_revision: Union[str, None] = 'e9e52fbe8017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standard_messages', 'message',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standard_messages', 'message',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
