"""empty message

Revision ID: 7706e10b5daa
Revises: 9332515a9165
Create Date: 2024-01-14 22:57:49.125366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7706e10b5daa'
down_revision: Union[str, None] = '9332515a9165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionaires',
    sa.Column('questionaire_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('questionare_name', sa.String(length=256), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('questionaire_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('questionaire_id', sa.BIGINT(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['questionaire_id'], ['questionaires.questionaire_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('answer_options',
    sa.Column('answer_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_options')
    op.drop_table('questions')
    op.drop_table('questionaires')
    # ### end Alembic commands ###
