"""empty message

Revision ID: 84f23f027241
Revises: e30b42e08a2a
Create Date: 2024-03-06 22:08:25.448246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84f23f027241'
down_revision: Union[str, None] = 'e30b42e08a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ntr_records',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('negative_thought', sa.TEXT(), nullable=False),
    sa.Column('reframing', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ntr_records')
    # ### end Alembic commands ###
