"""empty message

Revision ID: 9087ce4cb9bb
Revises: 91ae86f3a8cb
Create Date: 2024-01-08 17:28:22.672915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9087ce4cb9bb'
down_revision: Union[str, None] = '91ae86f3a8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_buttonss',
    sa.Column('key', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('menu_key', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('button_text', sa.String(length=256), nullable=False),
    sa.Column('callback_data', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key', 'menu_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_buttonss')
    # ### end Alembic commands ###
