"""empty message

Revision ID: 91ae86f3a8cb
Revises: c8685112ac8b
Create Date: 2024-01-08 11:59:41.359569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ae86f3a8cb'
down_revision: Union[str, None] = 'c8685112ac8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_messages', sa.Column('comment', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_messages', 'comment')
    # ### end Alembic commands ###
