"""empty message

Revision ID: 97e735cb03f6
Revises: 5400d88d7eb7
Create Date: 2024-02-28 23:37:02.612650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97e735cb03f6'
down_revision: Union[str, None] = '5400d88d7eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_records',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('emoton', sa.String(length=16), nullable=False),
    sa.Column('what_thinking', sa.TEXT(), nullable=False),
    sa.Column('what_doing', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotion_records')
    # ### end Alembic commands ###
