"""empty message

Revision ID: a574ff8ecb12
Revises: 68f5dd99428b
Create Date: 2024-02-05 11:22:52.114152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a574ff8ecb12'
down_revision: Union[str, None] = '68f5dd99428b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_polls',
    sa.Column('poll_id', sa.BIGINT(), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('selected_answer', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['communication_history.message_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('poll_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_polls')
    # ### end Alembic commands ###
