"""empty message

Revision ID: b3f802017ffe
Revises: b829a9b8f0be
Create Date: 2024-02-05 11:57:25.724327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f802017ffe'
down_revision: Union[str, None] = 'b829a9b8f0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_polls', sa.Column('user_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'sent_polls', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sent_polls', type_='foreignkey')
    op.drop_column('sent_polls', 'user_id')
    # ### end Alembic commands ###
