"""empty message

Revision ID: b829a9b8f0be
Revises: 6251d0e33033
Create Date: 2024-02-05 11:51:41.709649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b829a9b8f0be'
down_revision: Union[str, None] = '6251d0e33033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sent_polls_message_id_fkey', 'sent_polls', type_='foreignkey')
    op.create_foreign_key(None, 'sent_polls', 'communication_history', ['message_id'], ['message_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sent_polls', type_='foreignkey')
    op.create_foreign_key('sent_polls_message_id_fkey', 'sent_polls', 'communication_history', ['message_id'], ['message_id'])
    # ### end Alembic commands ###
