"""empty message

Revision ID: c46c7cba6e1c
Revises: 5d6d82476c55
Create Date: 2024-02-02 23:16:06.431963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46c7cba6e1c'
down_revision: Union[str, None] = '5d6d82476c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communication_history', 'text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communication_history', 'text',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
