"""empty message

Revision ID: c8685112ac8b
Revises: 61cbb46c9311
Create Date: 2024-01-08 11:57:34.823460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8685112ac8b'
down_revision: Union[str, None] = '61cbb46c9311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_messages',
    sa.Column('key', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_messages')
    # ### end Alembic commands ###
