"""empty message

Revision ID: d2a6a3db16c6
Revises: 034e1d94dfc7
Create Date: 2024-02-05 10:51:07.945098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a6a3db16c6'
down_revision: Union[str, None] = '034e1d94dfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_polls',
    sa.Column('poll_id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('selected_answer', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['communication_history.message_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('poll_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_polls')
    # ### end Alembic commands ###
