"""empty message

Revision ID: d4d9015eadc3
Revises: d2a6a3db16c6
Create Date: 2024-02-05 11:02:40.729636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d9015eadc3'
down_revision: Union[str, None] = 'd2a6a3db16c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_polls', sa.Column('message_id', sa.BIGINT(), nullable=False))
    op.drop_constraint('sent_polls_poll_id_fkey', 'sent_polls', type_='foreignkey')
    op.create_foreign_key(None, 'sent_polls', 'communication_history', ['message_id'], ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sent_polls', type_='foreignkey')
    op.create_foreign_key('sent_polls_poll_id_fkey', 'sent_polls', 'communication_history', ['poll_id'], ['message_id'])
    op.drop_column('sent_polls', 'message_id')
    # ### end Alembic commands ###
