"""empty message

Revision ID: e30b42e08a2a
Revises: 4248d44ccc08
Create Date: 2024-03-06 15:08:51.801153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30b42e08a2a'
down_revision: Union[str, None] = '4248d44ccc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_messages_user_from_fkey', 'feedback_messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('feedback_messages_user_from_fkey', 'feedback_messages', 'users', ['user_from'], ['user_id'])
    # ### end Alembic commands ###
