"""empty message

Revision ID: e9e52fbe8017
Revises: 1097aa640207
Create Date: 2024-01-23 10:55:32.664858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e52fbe8017'
down_revision: Union[str, None] = '1097aa640207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_history',
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('user_from', sa.BIGINT(), nullable=False),
    sa.Column('user_to', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_from', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_to', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['users.user_id'], name='messages_user_from_fkey'),
    sa.ForeignKeyConstraint(['user_to'], ['users.user_id'], name='messages_user_to_fkey'),
    sa.PrimaryKeyConstraint('message_id', name='messages_pkey')
    )
    op.drop_table('communication_history')
    # ### end Alembic commands ###
