"""empty message

Revision ID: f3a0c9f532f1
Revises: c06084ba0054
Create Date: 2024-02-11 11:20:47.141574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a0c9f532f1'
down_revision: Union[str, None] = 'c06084ba0054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('order', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'order')
    # ### end Alembic commands ###
